In [1]:
import numpy as np

In [2]:
from astropy import constants as const
from astropy import units as u
from math import pi

# Constantes

r_s = const.R_sun.to(u.m).value.item() #UA
m_s= const.M_sun.to(u.kg).value.item() #kg
M_t= const.M_earth.to(u.kg).value.item() #kg
R_t= const.R_earth.to(u.m).value.item() #km
a=1.496e+11#m

In [3]:
import pandas as pd

In [4]:
df_solar=pd.read_csv('sigma_sistema_solar.csv')

In [5]:
df_solar

,Unnamed: 0,name,rho_core_mean,cp_core_mean,T_cmb,P_cmb,Ric,Rc,D,V,sigma
0,0,Terra,11145.477629,1119.010063,4896.624938,1.354078e+11,1.410773e+06,3.520340e+06,2.109567e+06,5.294,1.483458e+06
1,1,Venus,NaN,NaN,NaN,NaN,0.000000e+00,3.012636e+06,3.012636e+06,NaN,NaN
2,2,mercury,9109.775026,908.980056,2076.517878,9.196088e+09,8.170758e+05,1.756468e+06,9.393925e+05,8.132,1.162333e+06
3,3,mars,8161.178387,922.836331,2301.256716,2.237380e+10,0.000000e+00,1.563256e+06,1.563256e+06,7.473,1.230997e+06
4,4,moon,8117.562400,894.625378,1891.745508,5.049640e+09,0.000000e+00,5.044434e+05,5.044434e+05,8.132,1.173822e+06
5,5,europa,7638.200954,889.571255,1852.153405,3.670332e+09,0.000000e+00,5.478610e+05,5.478610e+05,8.132,1.176351e+06
6,6,calisto,7566.343408,916.950091,1968.083708,5.715624e+09,0.000000e+00,4.837163e+05,4.837163e+05,8.132,1.169014e+06
7,7,Io,7450.033265,960.141896,1402.092974,8.126467e+09,1.787854e+06,3.240058e+06,1.452203e+06,8.132,1.206854e+06
8,8,ganimedes,7801.655849,961.819254,2129.860267,7.321830e+09,0.000000e+00,5.068215e+05,5.068215e+05,8.132,1.159109e+06

In [6]:
df_solar.iloc[0]

Unnamed: 0                         0
name                           Terra
rho_core_mean           11145.477629
cp_core_mean             1119.010063
T_cmb                    4896.624938
P_cmb            135407837772.624893
Ric                   1410772.891586
Rc                    3520339.832276
D                      2109566.94069
V                              5.294
sigma                 1483457.665989
Name: 0, dtype: object

In [7]:
def campo_radial(sigma, D, rho, R_m, r, K):
    
    Br=((K*R_m**2*D**2)/(2*sigma*r**3))*(np.sqrt(rho/mi_0)) #Tesla

    return Br

# Application for Solar System Objects
- Using parameters obtained from the literature for the internal structure of the objects. Represented by 1
- Using parameters obtained from the ROWs model. Represented by 2
- Em ambos os casos, serão os dois diferentes valores de Rm propostos. Ao todo serão 4 campos radiais propostos.
Para determinar $U_{rm, dynamo}$, foi utilizada uma aproximação, considerando o valor do número de Reynolds magnético $R_{m}=800$ para planetas semelhantes à Terra e super-Terras, um valor consistente com os resultados obtidos no artigo \citep[]{christensen2010dynamo} (valor de $R_{m}$ obtido para a Terra). Para satélites, foi utilizado um intervalo de valores entre $R_{m}=10$ e $R_{m}=100$, consistente com o valor de Rm presente em \citet{trinh2024critical}. Para Marte, foi utilizado um intervalo de valores de $R_{m}=100$ a $R_{m}=800$ devido à falta de valores disponíveis na literatura. Finalmente, o Rm estimado para Mercúrio a partir de \citet{takahashi2019mercury} é $\approx 100$ \citep[]. Especificamente para o mercúrio, os valores de $Rm$, $Rci$, $Rc$ e $D$ encontrados em \citet{takahashi2019mercury} foram usados para seu estudo e determinação de seu campo. Portanto, $U_{rm, dynamo}$ é dado por

# Calibração de K para a terra

In [19]:
Rd=0.55*R_t # m
Rdi=0.19*R_t # m
rho=11000 # kg/m^3
D=Rd-Rdi # m
mi_0=4*np.pi*10**(-7)
R_m_terra=800 #ad
B_terra=5*10**(-5) # Tesla
sigma_terra=6*10**5 #(S/m)

# U=\frac{R_m}{\mu_0\sigma(T,V) D}

In [20]:
R_m_terra/(mi_0*sigma_terra*D)*10**3

0.46209902023502675

In [17]:
K1=np.around(((2*B_terra*sigma_terra*R_t**3)/(R_m_terra**2*D**2))*(np.sqrt(mi_0/rho)), 3)

In [18]:
K1

np.float64(0.123)

In [21]:
Rd=0.55*R_t # m
Rdi=0.19*R_t # m
rho=11000 # kg/m^3
D=Rd-Rdi # m
mi_0=4*np.pi*10**(-7)
R_m_terra=800 #ad
B_terra=3.8*10**(-5) # Tesla
sigma_terra=1.5*10**6 #(S/m)

In [22]:
R_m_terra/(mi_0*sigma_terra*D)*10**3

0.1848396080940107

In [20]:
K2=np.around(((2*B_terra*sigma_terra*R_t**3)/(R_m_terra**2*D**2))*(np.sqrt(mi_0/rho)), 3)

In [21]:
K2

np.float64(0.094)

In [22]:
resultados={'name':[], 'B1':[], 'B2':[]}

# Mercurio

# Following the proposed methodology: Finally, the $Rm$ estimated for Mercury, based on \citet{takahashi2019mercury}, is $\approx 100$ \citep[]. Specifically for Mercury, the values of $Rm$, $Rci$, $Rc$, and $D$ found in \citet{takahashi2019mercury} were used for the study and determination of its magnetic field.

In [23]:
df_solar.iloc[2]

Unnamed: 0                       2
name                       mercury
rho_core_mean          9109.775026
cp_core_mean            908.980056
T_cmb                  2076.517878
P_cmb            9196088015.668716
Ric                   817075.80072
Rc                  1756468.338074
D                    939392.537354
V                            8.132
sigma               1162332.614823
Name: 2, dtype: object

In [24]:
# Mercury 1
R_mercury=0.38*R_t
sigma=1106516
Rd=0.75*R_mercury 
Rdi=0.5*R_mercury 
D=Rd-Rdi
rho=9108.0 
R_m=100

In [25]:
B_r_sup1=campo_radial(sigma, D, rho, R_m, R_mercury, K2)
B_r_sup1

np.float64(9.325064305772643e-07)

In [26]:
# Mercury 2
R_mercury=0.38*R_t
sigma=df_solar.iloc[2]['sigma']
Rd=df_solar.iloc[2]['Rc']
Rdi=df_solar.iloc[2]['Ric']
D=Rd-Rdi
rho=df_solar.iloc[2]['rho_core_mean']
R_m=100
name='Mercury'

In [27]:
B_r_sup2=campo_radial(sigma, D, rho, R_m, R_mercury, K2)
B_r_sup2

np.float64(2.13395755530784e-06)

In [28]:
resultados['name'].append(name)
resultados['B1'].append(B_r_sup1)
resultados['B2'].append(B_r_sup2)

In [29]:
resultados

{'name': ['Mercury'],
 'B1': [np.float64(9.325064305772643e-07)],
 'B2': [np.float64(2.13395755530784e-06)]}

#  Venus

# Venus 1
There are no values listed for the item.

In [30]:
df_solar.iloc[1]

Unnamed: 0                    1
name                      Venus
rho_core_mean               NaN
cp_core_mean                NaN
T_cmb                       NaN
P_cmb                       NaN
Ric                         0.0
Rc               3012636.025146
D                3012636.025146
V                           NaN
sigma                       NaN
Name: 1, dtype: object

In [31]:
# Venus 2
R_v=0.95*R_t
mi_0=4*np.pi*10**(-7) 
sigma=5*10**5 
D=0
rho=8000 
name='Venus'
B_r_sup=campo_radial(sigma, D, rho, R_m, R_mercury, K2)
B_r_sup

np.float64(0.0)

In [32]:
resultados['name'].append(name)
resultados['B1'].append(np.nan)
resultados['B2'].append(0.0)

# Mars

# Mars 1
There are no values listed for the item.

In [33]:
df_solar.iloc[3]

Unnamed: 0                        3
name                           mars
rho_core_mean           8161.178387
cp_core_mean             922.836331
T_cmb                   2301.256716
P_cmb            22373803783.860813
Ric                             0.0
Rc                   1563255.592883
D                    1563255.592883
V                             7.473
sigma                1230996.768957
Name: 3, dtype: object

In [34]:
# Mars 2.1
Rp=0.532*R_t
sigma=df_solar.iloc[3]['sigma']
Rd=df_solar.iloc[3]['Rc']
Rdi=df_solar.iloc[3]['Ric']
D=Rd-Rdi
rho=df_solar.iloc[3]['rho_core_mean']
R_m=100

In [35]:
B_r_sup_2_1=campo_radial(sigma, D, rho, R_m, Rp, K2)
B_r_sup_2_1

np.float64(1.9247022824832793e-06)

In [36]:
# Mars 2.2
Rp=0.532*R_t
sigma=df_solar.iloc[3]['sigma']
Rd=df_solar.iloc[3]['Rc']
Rdi=df_solar.iloc[3]['Ric']
D=Rd-Rdi
rho=df_solar.iloc[3]['rho_core_mean']
R_m=800

In [37]:
B_r_sup_2_2=campo_radial(sigma, D, rho, R_m, Rp, K2)
B_r_sup_2_2

np.float64(0.00012318094607892987)

In [38]:
name='mars'

In [39]:
resultados['name'].append(name)
resultados['B1'].append(np.nan)
resultados['B2'].append([B_r_sup_2_1, B_r_sup_2_2])

# Moon

# Moon 1
There are no values listed for the item.

In [40]:
df_solar.iloc[4]

Unnamed: 0                       4
name                          moon
rho_core_mean            8117.5624
cp_core_mean            894.625378
T_cmb                  1891.745508
P_cmb            5049640379.346342
Ric                            0.0
Rc                   504443.414627
D                    504443.414627
V                            8.132
sigma               1173822.098401
Name: 4, dtype: object

In [41]:
# Moon 2.1
Rp=0.27*R_t
sigma=df_solar.iloc[4]['sigma']
Rd=df_solar.iloc[4]['Rc']
Rdi=df_solar.iloc[4]['Ric']
D=Rd-Rdi
rho=df_solar.iloc[4]['rho_core_mean']
R_m=10

In [42]:
B_r_sup_2_1=campo_radial(sigma, D, rho, R_m, Rp, K2)
B_r_sup_2_1

np.float64(1.6034783898646e-08)

In [43]:
# Moon 2.2
Rp=0.27*R_t
sigma=df_solar.iloc[4]['sigma']
Rd=df_solar.iloc[4]['Rc']
Rdi=df_solar.iloc[4]['Ric']
D=Rd-Rdi
rho=df_solar.iloc[4]['rho_core_mean']
R_m=100

In [44]:
B_r_sup_2_2=campo_radial(sigma, D, rho, R_m, Rp, K2)
B_r_sup_2_2

np.float64(1.6034783898646002e-06)

In [45]:
name='moon'

In [46]:
resultados['name'].append(name)
resultados['B1'].append(np.nan)
resultados['B2'].append([B_r_sup_2_1, B_r_sup_2_2])

# Ganymedes

In [47]:
df_solar.iloc[8]

Unnamed: 0                      8
name                    ganimedes
rho_core_mean         7801.655849
cp_core_mean           961.819254
T_cmb                 2129.860267
P_cmb            7321830242.18649
Ric                           0.0
Rc                  506821.531475
D                   506821.531475
V                           8.132
sigma              1159108.913553
Name: 8, dtype: object

In [48]:
# Ganymedes 1.1
Rp=0.413*R_t
sigma=1102615
Rd=0.3*Rp 
Rdi=0.0*Rp 
D=Rd-Rdi
rho=7802 
R_m=10

In [49]:
B_r_sup_1_1=campo_radial(sigma, D, rho, R_m, Rp, K2)
B_r_sup_1_1

np.float64(1.1475540135614644e-08)

In [50]:
# Ganymedes 1.2
Rp=0.413*R_t
sigma=1102615
Rd=0.3*Rp 
Rdi=0.0*Rp 
D=Rd-Rdi
rho=7802 
R_m=100

In [51]:
B_r_sup_1_2=campo_radial(sigma, D, rho, R_m, Rp, K2)
B_r_sup_1_2

np.float64(1.1475540135614642e-06)

In [52]:
# Ganymedes 2.1
Rp=0.413*R_t
sigma=df_solar.iloc[8]['sigma']
Rd=df_solar.iloc[8]['Rc']
Rdi=df_solar.iloc[8]['Ric']
D=Rd-Rdi
rho=df_solar.iloc[8]['rho_core_mean']
R_m=10

In [53]:
B_r_sup_2_1=campo_radial(sigma, D, rho, R_m, Rp, K2)
B_r_sup_2_1

np.float64(4.490017783536801e-09)

In [54]:
# Ganymedes 2.2
Rp=0.413*R_t
sigma=df_solar.iloc[8]['sigma']
Rd=df_solar.iloc[8]['Rc']
Rdi=df_solar.iloc[8]['Ric']
D=Rd-Rdi
rho=df_solar.iloc[8]['rho_core_mean']
R_m=100

In [55]:
B_r_sup_2_2=campo_radial(sigma, D, rho, R_m, Rp, K2)
B_r_sup_2_2

np.float64(4.490017783536801e-07)

In [56]:
name='Ganymedes'

In [57]:
resultados['name'].append(name)
resultados['B1'].append([B_r_sup_1_1, B_r_sup_1_2])
resultados['B2'].append([B_r_sup_2_1, B_r_sup_2_2])

# IO

# Io 1
There are no values listed for the item.

In [58]:
df_solar.iloc[7]

Unnamed: 0                       7
name                            Io
rho_core_mean          7450.033265
cp_core_mean            960.141896
T_cmb                  1402.092974
P_cmb            8126466816.053209
Ric                  1787854.28934
Rc                  3240057.773401
D                   1452203.484062
V                            8.132
sigma               1206854.107782
Name: 7, dtype: object

In [59]:
# IO 2.1

Rp=0.286*R_t
sigma=df_solar.iloc[7]['sigma']
Rd=df_solar.iloc[7]['Rc']
Rdi=df_solar.iloc[7]['Ric']
D=Rd-Rdi
rho=df_solar.iloc[7]['rho_core_mean']
R_m=10

In [60]:
B_r_sup_2_1=campo_radial(sigma, D, rho, R_m, Rp, K2)
B_r_sup_2_1

np.float64(1.0418378610301131e-07)

In [61]:
# IO 2.2

Rp=0.286*R_t
sigma=df_solar.iloc[7]['sigma']
Rd=df_solar.iloc[7]['Rc']
Rdi=df_solar.iloc[7]['Ric']
D=Rd-Rdi
rho=df_solar.iloc[7]['rho_core_mean']
R_m=100

In [62]:
B_r_sup_2_2=campo_radial(sigma, D, rho, R_m, Rp, K2)
B_r_sup_2_2

np.float64(1.041837861030113e-05)

In [63]:
name='Io'

In [64]:
resultados['name'].append(name)
resultados['B1'].append(np.nan)
resultados['B2'].append([B_r_sup_2_1, B_r_sup_2_2])

# EUROPE

# EUROPE 1

There are no values listed for the item.

In [65]:
df_solar.iloc[5]

Unnamed: 0                       5
name                        europa
rho_core_mean          7638.200954
cp_core_mean            889.571255
T_cmb                  1852.153405
P_cmb            3670332239.000185
Ric                            0.0
Rc                   547861.029458
D                    547861.029458
V                            8.132
sigma               1176350.791247
Name: 5, dtype: object

In [66]:
# EUROPE 2.1

Rp=0.25*R_t
sigma=df_solar.iloc[5]['sigma']
Rd=df_solar.iloc[5]['Rc']
Rdi=df_solar.iloc[5]['Ric']
D=Rd-Rdi
rho=df_solar.iloc[5]['rho_core_mean']
R_m=10

In [67]:
B_r_sup_2_1=campo_radial(sigma, D, rho, R_m, Rp, K2)
B_r_sup_2_1

np.float64(2.306207802363628e-08)

In [68]:
# EUROPE 2.2
Rp=0.25*R_t
sigma=df_solar.iloc[5]['sigma']
Rd=df_solar.iloc[5]['Rc']
Rdi=df_solar.iloc[5]['Ric']
D=Rd-Rdi
rho=df_solar.iloc[5]['rho_core_mean']
R_m=100

In [69]:
B_r_sup_2_2=campo_radial(sigma, D, rho, R_m, Rp, K2)
B_r_sup_2_2

np.float64(2.306207802363628e-06)

In [70]:
campo_radial(sigma, 0, rho, R_m, Rp, K2)

np.float64(0.0)

In [71]:
name='Europe'

In [72]:
resultados['name'].append(name)
resultados['B1'].append(np.nan)
resultados['B2'].append([B_r_sup_2_1, B_r_sup_2_2])

# CALLISTO

# CALLISTO 1

There are no values ​​listed for the item.

In [73]:
df_solar.iloc[6]

Unnamed: 0                       6
name                       calisto
rho_core_mean          7566.343408
cp_core_mean            916.950091
T_cmb                  1968.083708
P_cmb            5715623649.806154
Ric                            0.0
Rc                   483716.261092
D                    483716.261092
V                            8.132
sigma               1169013.642494
Name: 6, dtype: object

In [74]:
# CALLISTO 2.1

Rp=0.38*R_t
sigma=df_solar.iloc[6]['sigma']
Rd=df_solar.iloc[6]['Rc']
Rdi=df_solar.iloc[6]['Ric']
D=Rd-Rdi
rho=df_solar.iloc[6]['rho_core_mean']
R_m=10

In [75]:
B_r_sup_2_1=campo_radial(sigma, D, rho, R_m, Rp, K2)
B_r_sup_2_1

np.float64(5.12711410793828e-09)

In [76]:
# CALLISTO 2.2

Rp=0.38*R_t
sigma=df_solar.iloc[6]['sigma']
Rd=df_solar.iloc[6]['Rc']
Rdi=df_solar.iloc[6]['Ric']
D=Rd-Rdi
rho=df_solar.iloc[6]['rho_core_mean']
R_m=100

In [77]:
B_r_sup_2_2=campo_radial(sigma, D, rho, R_m, Rp, K2)
B_r_sup_2_2

np.float64(5.127114107938279e-07)

In [78]:
name='Calisto'

In [79]:
resultados['name'].append(name)
resultados['B1'].append(np.nan)
resultados['B2'].append([B_r_sup_2_1, B_r_sup_2_2])

In [81]:
import pandas as pd

In [83]:
df=pd.DataFrame(resultados)

In [84]:
def fmt(x):
    if isinstance(x, list):
        return [f'{v:.2e}' for v in x]
    elif isinstance(x, (float, np.floating)) and not np.isnan(x) and x != 0.0:
        return f'{x:.2e}'
    else:
        return x

df = pd.DataFrame(resultados)  # recria do dicionário original
df_fmt = df.map(fmt)
print(df_fmt.to_string(index=False))

     name                   B1                   B2
  Mercury             9.33e-07             2.13e-06
    Venus                  NaN                  0.0
     mars                  NaN [1.92e-06, 1.23e-04]
     moon                  NaN [1.60e-08, 1.60e-06]
Ganymedes [1.15e-08, 1.15e-06] [4.49e-09, 4.49e-07]
       Io                  NaN [1.04e-07, 1.04e-05]
   Europe                  NaN [2.31e-08, 2.31e-06]
  Calisto                  NaN [5.13e-09, 5.13e-07]

In [85]:
df_fmt

        name                    B1                    B2
0    Mercury              9.33e-07              2.13e-06
1      Venus                   NaN                   0.0
2       mars                   NaN  [1.92e-06, 1.23e-04]
3       moon                   NaN  [1.60e-08, 1.60e-06]
4  Ganymedes  [1.15e-08, 1.15e-06]  [4.49e-09, 4.49e-07]
5         Io                   NaN  [1.04e-07, 1.04e-05]
6     Europe                   NaN  [2.31e-08, 2.31e-06]
7    Calisto                   NaN  [5.13e-09, 5.13e-07]

In [209]:
df_fmt.to_csv('dados_campo_sistema_solar.csv')